import type { NextPage } from 'next'
import Head from 'next/head'
import useGame from '../context/useGame'
import { GameState } from '../utils/enum'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { randomId } from '../utils'

const Home: NextPage = () => {
  const router = useRouter()
  const { state } = useGame()

  useEffect(() => {
    const roomId = randomId()
    router.push(`/room/${roomId}`)
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold">
          Tic Tac Toe: {state}
        </h1>

        <div className="space-y-6">
          {state === GameState.READY && (
            <h3 className="text-lg font-medium">Waiting for an opponent...</h3>
          )}
        </div>
      </main>
    </>
  )
}

export default Home
